"""琅嬛 V97 brand: frosted-glass books + leaf on an emerald→mint gradient.

Builds every launcher / splash resource from the chosen artwork
(tools/brand/source/glass_books_v97.png, 1024 px):

  * ic_launcher_background_v97.xml  vector linear gradient fitted to the artwork's background
  * ic_launcher_foreground_v97.png  the glass art lifted off the gradient (per-pixel colour-to-alpha
                                    against a fitted background model), mdpi–xxxhdpi, 108 dp canvas
  * ic_launcher_monochrome_v97.xml  Android 13 themed-icon silhouette (two leaning books + leaf)
  * mipmap-*/ic_launcher(_round).png legacy icons, ic_launcher-playstore.png (512)
  * drawable-nodpi/splash_glass_v97.png  splash icon: the full icon tile on a 288 dp canvas
  * LanghuanMarkV97 path data (printed) for the in-app mark

usage: python3 tools/brand/glass_icon_v97.py <app/src/main>      (numpy, Pillow, scipy, shapely)
"""
import os, sys, math
import numpy as np
from PIL import Image, ImageDraw, ImageFilter
from scipy import ndimage
from shapely.geometry import Polygon, Point, box
from shapely.affinity import rotate, translate, scale as sscale
from shapely.ops import unary_union

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'source', 'glass_books_v97.png')
main = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, '..', '..', 'app', 'src', 'main')
res = os.path.join(main, 'res')

src = Image.open(SRC).convert('RGB')
im = np.asarray(src).astype(np.float64)
N = im.shape[0]
yy, xx = np.mgrid[0:N, 0:N] / (N - 1.0)
art_box = np.zeros((N, N), bool); art_box[150:860, 140:890] = True
outside = ~art_box

# ---------------------------------------------------------------- 1. background gradient (vector)
# Diagonal linear gradient (bottom-left deep emerald → top-right mint), six evenly spaced stops
# least-squares fitted to the artwork's background pixels.
KS = np.linspace(0, 1, 6)
def hat(t): return np.stack([np.clip(1 - np.abs(t - k) / (KS[1] - KS[0]), 0, None) for k in KS], -1)
tdiag = (xx + (1 - yy)) / 2
stops = np.array([np.linalg.lstsq(hat(tdiag[outside]), im[..., c][outside], rcond=None)[0] for c in range(3)]).T
stops = np.clip(np.round(stops), 0, 255).astype(int)
hexs = ['#FF%02X%02X%02X' % tuple(s) for s in stops]
# The source's 1024 px frame is the visible 72 dp viewport (18..90 on the 108 dp canvas); the
# gradient runs corner to corner of that viewport and clamps beyond it.
items = '\n'.join(f'                    <item android:offset="{k:.1f}" android:color="{h}" />' for k, h in zip(KS, hexs))
bg_xml = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- 琅嬛 V97 adaptive-icon background: emerald → mint diagonal gradient fitted to the artwork.
     Generated by tools/brand/glass_icon_v97.py; edit there and regenerate. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="18"
                android:startY="90"
                android:endX="90"
                android:endY="18"
                android:tileMode="clamp">
{items}
            </gradient>
        </aapt:attr>
    </path>
</vector>
'''
open(os.path.join(res, 'drawable', 'ic_launcher_background_v97.xml'), 'w').write(bg_xml)

# ---------------------------------------------------------------- 2. lift the glass art (RGBA)
def basis(x, y, deg=3): return np.stack([x ** i * y ** j for i in range(deg + 1) for j in range(deg + 1 - i)], -1)
B = basis(xx, yy)
coef = [np.linalg.lstsq(B[outside][::3], im[..., c][outside][::3], rcond=None)[0] for c in range(3)]
bgm = np.stack([B @ coef[c] for c in range(3)], -1)
d = im - bgm
NOISE = 5.0
dd = np.sign(d) * np.clip(np.abs(d) - NOISE, 0, None)
lim = np.where(dd > 0, 255 - bgm, bgm)
alpha = np.clip((np.abs(dd) / np.maximum(lim, 1)).max(-1), 0, 1)
sig = ndimage.binary_closing(alpha > 0.03, iterations=6)
lab, n = ndimage.label(sig)
sizes = ndimage.sum(np.ones_like(alpha), lab, range(1, n + 1))
keep = ndimage.binary_dilation(np.isin(lab, 1 + np.where(sizes > 800)[0]), iterations=10)
soft = np.asarray(Image.fromarray((keep * 255).astype(np.uint8)).filter(ImageFilter.GaussianBlur(4))) / 255.0
alpha = alpha * soft
fgc = np.clip(bgm + (im - bgm) / np.maximum(alpha, 1e-3)[..., None], 0, 255)
fgc[alpha < 1e-3] = 255
art = Image.fromarray(np.dstack([fgc, alpha * 255]).astype(np.uint8), 'RGBA')

# Placement: the source frame maps onto the 72 dp viewport, enlarged 10 % around the frame centre
# for small-size legibility; the art then spans r ≈ 30 dp, inside the 66 dp safe zone.
ENLARGE = 1.10
def foreground(px):  # px = canvas size (108 dp)
    k = ENLARGE * (px * 72 / 108) / N
    S = 4  # supersample, then downscale once
    big = art.convert('RGBa').resize((round(N * k * S),) * 2, Image.LANCZOS)
    canvas = Image.new('RGBa', (px * S, px * S), (0, 0, 0, 0))
    off = round(px * S / 2 - big.width / 2)
    canvas.paste(big, (off, off))
    return canvas.resize((px, px), Image.LANCZOS).convert('RGBA')

for dens, px in [('mdpi', 108), ('hdpi', 162), ('xhdpi', 216), ('xxhdpi', 324), ('xxxhdpi', 432)]:
    os.makedirs(os.path.join(res, f'drawable-{dens}'), exist_ok=True)
    foreground(px).save(os.path.join(res, f'drawable-{dens}', 'ic_launcher_foreground_v97.png'), optimize=True)

a = np.asarray(foreground(432))[..., 3]
ys, xs = np.where(a >= 40)
r_dp = np.sqrt((xs - 216) ** 2 + (ys - 216) ** 2).max() / 4
print(f'foreground extent r = {r_dp:.1f} dp (safe zone 33 dp)')

# ---------------------------------------------------------------- 3. monochrome silhouette
def rrect(w, h, r):
    return box(-w / 2, -h / 2, w / 2, h / 2).buffer(-r, join_style=1).buffer(r, resolution=16)

def book(cx, cy, ang, w=20.0, h=27.5):
    body = rrect(w, h, 2.6)
    spine = box(-w / 2 + 3.0, -h / 2 + 2.2, -w / 2 + 4.2, h / 2 - 2.2)            # spine groove
    pages = box(-w / 2 + 4.2, h / 2 - 3.0, w / 2 - 1.6, h / 2 - 2.0)              # page-edge groove
    ribbon = Polygon([(-w / 2 + 6.0, h / 2 - 1), (-w / 2 + 9.6, h / 2 - 1), (-w / 2 + 9.6, h / 2 + 4.6),
                      (-w / 2 + 7.8, h / 2 + 3.2), (-w / 2 + 6.0, h / 2 + 4.6)])
    shape = body.difference(spine).difference(pages)
    g = unary_union([shape, ribbon])
    return translate(rotate(g, ang, origin=(0, 0)), cx, cy), translate(rotate(body, ang, origin=(0, 0)), cx, cy)

def leaf(cx, cy, length, width, ang):
    pts = []
    for i in range(41):
        t = i / 40
        x = (t - 0.5) * length
        y = width / 2 * math.sin(math.pi * t) ** 0.9
        pts.append((x, y))
    for i in range(40, -1, -1):
        t = i / 40
        pts.append(((t - 0.5) * length, -width / 2 * math.sin(math.pi * t) ** 0.9))
    g = Polygon(pts)
    vein = box(-length * 0.38, -0.32, length * 0.30, 0.32)
    g = g.difference(vein)
    return translate(rotate(g, ang, origin=(0, 0)), cx, cy)

ANG = -24
back, back_body = book(44.0, 57.5, ANG)
front, front_body = book(62.0, 59.5, ANG)
back = back.difference(front_body.buffer(1.7, resolution=16))
def leaf_from(base, length, width, ang):  # leaf whose inner end sits at base
    dx, dy = math.cos(math.radians(ang)), math.sin(math.radians(ang))
    return leaf(base[0] + dx * length / 2, base[1] + dy * length / 2, length, width, ang)
STEM = (55.0, 42.2)
leaves = unary_union([leaf_from((STEM[0] - 0.6, STEM[1]), 10.5, 5.6, 232), leaf_from((STEM[0] + 0.6, STEM[1]), 13.0, 6.6, -50)])
print(f'leaf gap to books = {leaves.distance(unary_union([back_body, front_body])):.2f} dp')
books = unary_union([back, front])
mono_all = unary_union([books, leaves])
mx = max(Point(54, 54).distance(Point(p)) for g in getattr(mono_all, 'geoms', [mono_all]) for p in g.exterior.coords)
print(f'monochrome extent r = {mx:.1f} dp')

def path_of(geom, ox=0.0, oy=0.0):
    out = []
    for g in getattr(geom, 'geoms', [geom]):
        for ring in [g.exterior] + list(g.interiors):
            c = list(ring.coords)[:-1]
            out.append('M' + ' L'.join(f'{x - ox:.2f},{y - oy:.2f}' for x, y in c) + ' Z')
    return ' '.join(out)

mono_xml = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- 琅嬛 V97 themed-icon layer: two leaning books (spine, page edge, ribbon) and a two-leaf sprig.
     Generated by tools/brand/glass_icon_v97.py; edit there and regenerate. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#FF000000"
        android:fillType="evenOdd"
        android:pathData="{path_of(books)}" />
    <path
        android:fillColor="#FF000000"
        android:fillType="evenOdd"
        android:pathData="{path_of(leaves)}" />
</vector>
'''
open(os.path.join(res, 'drawable', 'ic_launcher_monochrome_v97.xml'), 'w').write(mono_xml)

# in-app mark: same geometry cropped to its bounds (square viewport)
minx, miny, maxx, maxy = mono_all.bounds
side = max(maxx - minx, maxy - miny) + 2
ox = (minx + maxx) / 2 - side / 2; oy = (miny + maxy) / 2 - side / 2
open(os.path.join(HERE, 'mark_v97.txt'), 'w').write(
    f'viewport {side:.2f}\nBOOKS {path_of(books, ox, oy)}\nLEAVES {path_of(leaves, ox, oy)}\n')

# ---------------------------------------------------------------- 4. legacy, round, Play store
def squircle_mask(n, frac=1.0, ss=4):
    m = Image.new('L', (n * ss, n * ss), 0)
    s = n * ss * frac; o = (n * ss - s) / 2
    pts = []
    for i in range(720):
        t = 2 * math.pi * i / 720
        c, sn = math.cos(t), math.sin(t)
        x = abs(c) ** (2 / 5) * (1 if c >= 0 else -1); y = abs(sn) ** (2 / 5) * (1 if sn >= 0 else -1)
        pts.append((o + s / 2 + x * s / 2, o + s / 2 + y * s / 2))
    ImageDraw.Draw(m).polygon(pts, fill=255)
    return m.resize((n, n), Image.LANCZOS)

def circle_mask(n, frac=1.0, ss=4):
    m = Image.new('L', (n * ss, n * ss), 0); s = n * ss * frac; o = (n * ss - s) / 2
    ImageDraw.Draw(m).ellipse([o, o, o + s, o + s], fill=255)
    return m.resize((n, n), Image.LANCZOS)

for dens, px in [('mdpi', 48), ('hdpi', 72), ('xhdpi', 96), ('xxhdpi', 144), ('xxxhdpi', 192)]:
    full = src.resize((px, px), Image.LANCZOS).convert('RGBA')
    for name, m in [('ic_launcher.png', squircle_mask(px, 44 / 48)), ('ic_launcher_round.png', circle_mask(px, 44 / 48))]:
        tile = full.resize((round(px * 44 / 48),) * 2, Image.LANCZOS)
        o = Image.new('RGBA', (px, px), (0, 0, 0, 0)); off = (px - tile.width) // 2
        o.paste(tile, (off, off)); o.putalpha(Image.fromarray(np.minimum(np.asarray(o)[..., 3], np.asarray(m))))
        o.save(os.path.join(res, f'mipmap-{dens}', name), optimize=True)
src.resize((512, 512), Image.LANCZOS).save(os.path.join(main, 'ic_launcher-playstore.png'), optimize=True)

# ---------------------------------------------------------------- 5. splash icon (288 dp canvas)
# The glass art is near-white, so on the pale #EEF5F1 splash surface it is drawn on its own
# emerald tile (the launcher icon, superellipse) — 132 dp, well inside the 192 dp splash circle.
C = 960  # 288 dp at 3.33 px/dp
tile_dp = 132
tpx = round(C * tile_dp / 288)
ss = 2
tile = src.resize((tpx * ss, tpx * ss), Image.LANCZOS).convert('RGBA')
tile.putalpha(squircle_mask(tpx * ss, 1.0, 2))
splash = Image.new('RGBA', (C * ss, C * ss), (0, 0, 0, 0))
off = (C * ss - tile.width) // 2
sh = Image.new('L', splash.size, 0)
sh.paste(tile.split()[3], (off, off + round(6 * C * ss / 288)))
sh = sh.filter(ImageFilter.GaussianBlur(14 * ss)).point(lambda v: v * 0.22)
splash = Image.composite(Image.new('RGBA', splash.size, (6, 40, 30, 255)), Image.new('RGBA', splash.size, (0, 0, 0, 0)), sh)
splash.alpha_composite(tile, (off, off))
splash = splash.resize((C, C), Image.LANCZOS)
splash.save(os.path.join(res, 'drawable-nodpi', 'splash_glass_v97.png'), optimize=True)
print('stops', hexs)
